// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dotNetStudy.Data;

#nullable disable

namespace dotNetStudy.Migrations
{
    [DbContext(typeof(AriaContext))]
    [Migration("20230530070154_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("dotNetStudy.Models.Avatar", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    b.Property<int>("BeardIndexMale")
                        .HasColumnType("int")
                        .HasColumnName("수염 파트");

                    b.Property<int>("ChestIndexMale")
                        .HasColumnType("int")
                        .HasColumnName("가슴 파트");

                    b.Property<int>("EyebrowIndexMale")
                        .HasColumnType("int")
                        .HasColumnName("눈 파트");

                    b.Property<int>("FacesIndexMale")
                        .HasColumnType("int")
                        .HasColumnName("얼굴 파트");

                    b.Property<int>("HairIndexMale")
                        .HasColumnType("int")
                        .HasColumnName("머리 파트");

                    b.Property<int>("HandsIndexMale")
                        .HasColumnType("int")
                        .HasColumnName("손 파트");

                    b.Property<bool>("IsMale")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("성별");

                    b.Property<int>("LegsIndexMale")
                        .HasColumnType("int")
                        .HasColumnName("다리 파트");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("캐릭터 소유 유저");

                    b.HasKey("Id");

                    b.ToTable("Avatars", (string)null);
                });

            modelBuilder.Entity("dotNetStudy.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    b.Property<string>("loginId")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("로그인 아이디");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("패스워드");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("dotNetStudy.TestClass.TestUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("테스트 이메일");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("테스트 네임");

                    b.HasKey("Id");

                    b.ToTable("TestUsers", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
